name: Compilar APK AVERIAS EMT

on:
  push:
    branches: [ "main", "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Preparar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Preparar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.9"

      - name: Descomprimir proyecto
        run: |
          unzip -o AVERIAS_EMT_ANDROID_v0.1_FUENTE.zip -d proyecto

      - name: Compilar APK
        working-directory: proyecto
        run: gradle assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: AVERIAS-EMT-APK
          path: proyecto/app/build/outputs/apk/debug/app-debug.apk
